AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  simple-websockets-chat-app

  SAM Template for simple-websockets-chat-app that has the DynamoDB table and Lambda
  functions needed to demonstrate the Websocket protocol on API Gateway.


Resources:
  SimpleChatCf:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: SimpleChatCf 
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: "$request.body.action"
  ConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref SimpleChatCf 
      RouteKey: $connect
      AuthorizationType: NONE
      OperationName: ConnectRoute
      Target: !Join
        - "/"
        - - "integrations"
          - !Ref ConnectInteg
          - !Ref ConnectResponse
  
  ConnectInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref SimpleChatCf 
      Description: Connect Integration
      IntegrationType: HTTP
      IntegrationMethod: POST
      IntegrationUri: https://us-central1-pie-ed-dev-221718.cloudfunctions.net/onconnect
      TemplateSelectionExpression: "$default"
      RequestTemplates:
        $default:
          connectionId: "$context.connectionId"

  ConnectResponse:
    Type: AWS::ApiGatewayV2::IntegrationResponse
    Properties: 
      ApiId: !Ref SimpleChatCf
      TemplateSelectionExpression: "${integration.response.statusCode}"
      IntegrationResponseKey: "$default"
        
  
  DisconnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref SimpleChatCf 
      RouteKey: $disconnect
      AuthorizationType: NONE
      OperationName: DisconnectRoute
      Target: !Join
        - "/"
        - - "integrations"
          - !Ref DisconnectInteg
  DisconnectInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref SimpleChatCf 
      Description: Disconnect Integration
      IntegrationType: HTTP
      IntegrationMethod: POST
      IntegrationUri: https://us-central1-pie-ed-dev-221718.cloudfunctions.net/ondisconnect
      TemplateSelectionExpression: "$default"
      RequestTemplates:
        $default:
          connectionId: "$context.connectionId"

  
  SendRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref SimpleChatCf 
      RouteKey: sendmessage
      AuthorizationType: NONE
      OperationName: SendRoute
      Target: !Join
        - "/"
        - - "integrations"
          - !Ref SendInteg
  SendInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref SimpleChatCf 
      Description: Send Integration
      IntegrationType: HTTP
      IntegrationMethod: POST
      ContentHandlingStrategy: CONVERT_TO_TEXT
      IntegrationUri: https://us-central1-pie-ed-dev-221718.cloudfunctions.net/ondisconnect
      TemplateSelectionExpression: "$default"
      RequestTemplates:
        $default:
          connectionId: "\\\\$context.connectionId"
          data: $input.body
          domainName: "$context.domainName", 
          stage: "$context.stage" 
  
  Deployment:
    Type: AWS::ApiGatewayV2::Deployment
    DependsOn:
      - ConnectRoute
      - SendRoute
      - DisconnectRoute
    Properties:
      ApiId: !Ref SimpleChatCf 
  Stage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      StageName: Dev 
      Description: Dev Stage
      DeploymentId: !Ref Deployment
      ApiId: !Ref SimpleChatCf 

Outputs:
  WebSocketURI:
    Description: "The WSS Protocol URI to connect to"
    Value:
      !Join [
        "",
        [
          "wss://",
          !Ref SimpleChatCf,
          ".execute-api.",
          !Ref "AWS::Region",
          ".amazonaws.com/",
          !Ref "Stage",
        ],
      ]
